<?php

use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\ChristeningController;
use App\Http\Controllers\BurialController;
use App\Http\Controllers\ConfirmationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\WeddingController;
use App\Http\Controllers\DocumentationController;
use Illuminate\Support\Facades\Route;

Route::view('/', 'landingPage')->name('landingPage');

Route::view('/developers', 'developers')->name('developers');

Route::view('/admin', 'auth.adminLogin')->name('admin.login');
Route::post('/admin/login', [AuthController::class, 'login'])->name('admin.login.submit');

Route::middleware('auth')->group(function () {
    Route::get('/sappcDashboard', [DashboardController::class, 'index'])->name('admin.dashboard');
    Route::get('/admin/dashboard/records', [DashboardController::class, 'records'])->name('admin.dashboard.records');
    Route::get('/admin/dashboard/search', [DashboardController::class, 'searchSAPPCData'])->name('admin.dashboard.search');
    Route::get('/admin/dashboard/stats/monthly', [DashboardController::class, 'monthlyStats'])->name('admin.dashboard.stats.monthly');
    Route::post('/admin/logout', [AuthController::class, 'logout'])->name('admin.logout');
    Route::get('/christening', [ChristeningController::class, 'index'])->name('admin.christening');
    Route::get('/christening/schedule', [ChristeningController::class, 'scheduleIndex'])->name('admin.christening.schedule');
    Route::get('/christening/certification', [ChristeningController::class, 'certificationIndex'])->name('admin.christening.certification');
    Route::get('/christening/payment', [ChristeningController::class, 'paymentIndex'])->name('admin.christening.payment');
    Route::get('/christening/application-form', [ChristeningController::class, 'applicationIndex'])->name('admin.christening.application');
    Route::get('/confirmation', [ConfirmationController::class, 'index'])->name('admin.confirmation');
    Route::get('/confirmation/schedule', [ConfirmationController::class, 'scheduleIndex'])->name('admin.confirmation.schedule');
    Route::get('/confirmation/certification', [ConfirmationController::class, 'certificationIndex'])->name('admin.confirmation.certification');
    Route::get('/confirmation/payment', [ConfirmationController::class, 'paymentIndex'])->name('admin.confirmation.payment');
    Route::get('/confirmation/application-form', [ConfirmationController::class, 'applicationIndex'])->name('admin.confirmation.application');
    Route::post('/confirmation/schedule-request', [ConfirmationController::class, 'scheduleConfirmation'])->name('admin.confirmation.schedule-request');
    Route::get('/confirmation/schedule-reserved-dates', [ConfirmationController::class, 'confirmationReservedDates'])->name('admin.confirmation.schedule-reserved-dates');
    Route::get('/confirmation/schedule-details', [ConfirmationController::class, 'confirmationScheduleDetails'])->name('admin.confirmation.schedule-details');
    Route::get('/confirmation/payment-details', [ConfirmationController::class, 'confirmationPaymentDetails'])->name('admin.confirmation.payment-details');
    Route::post('/confirmation/payment-save', [ConfirmationController::class, 'confirmationPaymentSave'])->name('admin.confirmation.payment-save');
    Route::get('/confirmation/confirmation-application', [ConfirmationController::class, 'confirmationApplicationDetails'])->name('admin.confirmation.application-details');
    Route::post('/confirmation/confirmation-application', [ConfirmationController::class, 'confirmationApplicationSave'])->name('admin.confirmation.application-save');
    Route::get('/confirmation/confirmation-arancel', [ConfirmationController::class, 'confirmationArancelDetails'])->name('admin.confirmation.arancel-details');
    Route::post('/confirmation/confirmation-arancel', [ConfirmationController::class, 'confirmationArancelSave'])->name('admin.confirmation.arancel-save');
    Route::get('/confirmation/certification-details', [ConfirmationController::class, 'confirmationCertificationDetails'])->name('admin.confirmation.certification-details');
    Route::post('/confirmation/record/delete', [ConfirmationController::class, 'deleteConfirmationRecord'])->name('admin.confirmation.record-delete');
    Route::get('/wedding', [WeddingController::class, 'index'])->name('admin.wedding');
    Route::get('/wedding/schedule', [WeddingController::class, 'scheduleIndex'])->name('admin.wedding.schedule');
    Route::get('/wedding/certification', [WeddingController::class, 'certificationIndex'])->name('admin.wedding.certification');
    Route::get('/wedding/payment', [WeddingController::class, 'paymentIndex'])->name('admin.wedding.payment');
    Route::get('/wedding/application-form', [WeddingController::class, 'applicationIndex'])->name('admin.wedding.application');
    Route::post('/wedding/schedule-request', [WeddingController::class, 'scheduleWedding'])->name('admin.wedding.schedule-request');
    Route::get('/wedding/schedule-reserved-dates', [WeddingController::class, 'weddingReservedDates'])->name('admin.wedding.schedule-reserved-dates');
    Route::get('/wedding/schedule-details', [WeddingController::class, 'weddingScheduleDetails'])->name('admin.wedding.schedule-details');
    Route::get('/wedding/payment-details', [WeddingController::class, 'weddingPaymentDetails'])->name('admin.wedding.payment-details');
    Route::post('/wedding/payment-save', [WeddingController::class, 'weddingPaymentSave'])->name('admin.wedding.payment-save');
    Route::get('/wedding/marriage-application', [WeddingController::class, 'weddingMarriageApplicationDetails'])->name('admin.wedding.marriage-application-details');
    Route::post('/wedding/marriage-application', [WeddingController::class, 'weddingMarriageApplicationSave'])->name('admin.wedding.marriage-application-save');
    Route::post('/wedding/marriage/certification-form', [WeddingController::class, 'weddingCertificationForm'])->name('admin.wedding.certification-form');
    Route::get('/wedding/marriage/certification-details', [WeddingController::class, 'weddingCertificationDetails'])->name('admin.wedding.certification-details');
    Route::post('/wedding/record/delete', [WeddingController::class, 'deleteWeddingRecord'])->name('admin.wedding.record-delete');
    Route::get('/burial', [BurialController::class, 'index'])->name('admin.burial');
    Route::get('/burial/schedule', [BurialController::class, 'scheduleIndex'])->name('admin.burial.schedule');
    Route::get('/burial/certification', [BurialController::class, 'certificationIndex'])->name('admin.burial.certification');
    Route::get('/burial/payment', [BurialController::class, 'paymentIndex'])->name('admin.burial.payment');
    Route::get('/burial/application-form', [BurialController::class, 'applicationIndex'])->name('admin.burial.application');
    Route::post('/burial/schedule-request', [BurialController::class, 'scheduleBurial'])->name('admin.burial.schedule-request');
    Route::get('/burial/schedule-reserved-dates', [BurialController::class, 'burialReservedDates'])->name('admin.burial.schedule-reserved-dates');
    Route::get('/burial/schedule-details', [BurialController::class, 'burialScheduleDetails'])->name('admin.burial.schedule-details');
    Route::get('/burial/payment-details', [BurialController::class, 'burialPaymentDetails'])->name('admin.burial.payment-details');
    Route::post('/burial/payment-save', [BurialController::class, 'burialPaymentSave'])->name('admin.burial.payment-save');
    Route::post('/burial/record/delete', [BurialController::class, 'deleteBurialRecord'])->name('admin.burial.record-delete');
    Route::get('/burial/application', [BurialController::class, 'burialApplicationDetails'])->name('admin.burial.application-details');
    Route::post('/burial/application', [BurialController::class, 'burialApplicationSave'])->name('admin.burial.application-save');
    Route::post('/burial/certification-form', [BurialController::class, 'burialCertificationForm'])->name('admin.burial.certification-form');
    Route::get('/burial/certification-details', [BurialController::class, 'burialCertificationDetails'])->name('admin.burial.certification-details');
    Route::get('/document', [DocumentationController::class, 'document'])->name('admin.document');
    Route::get('/document/report-window', [DocumentationController::class, 'reportWindow'])->name('admin.document.report-window');
    Route::get('/document/application-form-report', [DocumentationController::class, 'applicationFormReport'])->name('admin.document.application-form-report');
    Route::get('/document/burial-report', [DocumentationController::class, 'burialReport'])->name('admin.document.burial-report');
    Route::get('/certification', [ChristeningController::class, 'certificationPage'])->name('admin.certification');
    Route::get('/certification/report-window', [ChristeningController::class, 'certificationReportWindow'])->name('admin.certification.report-window');
    Route::get('/certification/records', [ChristeningController::class, 'certificationRecords'])->name('admin.certification.records');
    Route::get('/christening/next-reference-code', [ChristeningController::class, 'nextChristeningReferenceCode'])->name('admin.christening.next-reference-code');
    Route::get('/confirmation/next-reference-code', [ConfirmationController::class, 'nextConfirmationReferenceCode'])->name('admin.confirmation.next-reference-code');
    Route::get('/wedding/next-reference-code', [WeddingController::class, 'nextWeddingReferenceCode'])->name('admin.wedding.next-reference-code');
    Route::get('/burial/next-reference-code', [BurialController::class, 'nextBurialReferenceCode'])->name('admin.burial.next-reference-code');
    Route::post('/christening/schedule-request', [ChristeningController::class, 'scheduleChristening'])->name('admin.christening.schedule-request');
    Route::get('/christening/schedule-details', [ChristeningController::class, 'christeningScheduleDetails'])->name('admin.christening.schedule-details');
    Route::post('/christening/application-form', [ChristeningController::class, 'christeningApplicationForm'])->name('admin.christening.application-form');
    Route::get('/christening/application-details', [ChristeningController::class, 'christeningApplicationDetails'])->name('admin.christening.application-details');
    Route::get('/christening/payment-details', [ChristeningController::class, 'christeningPaymentDetails'])->name('admin.christening.payment-details');
    Route::post('/christening/payment-save', [ChristeningController::class, 'christeningPaymentSave'])->name('admin.christening.payment-save');
    Route::post('/christening/certification-form', [ChristeningController::class, 'christeningCertificationForm'])->name('admin.christening.certification-form');
    Route::get('/christening/certification-details', [ChristeningController::class, 'christeningCertificationDetails'])->name('admin.christening.certification-details');
    Route::post('/christening/record/delete', [ChristeningController::class, 'deleteChristeningRecord'])->name('admin.christening.record-delete');
    Route::get('/christening/schedule-reserved-dates', [ChristeningController::class, 'christeningReservedDates'])->name('admin.christening.schedule-reserved-dates');
    Route::post('/admin/dashboard/records/delete', [DashboardController::class, 'deleteRecord' ])->name('admin.dashboard.records.delete');
});
